USE [master]
GO
/****** Object:  Database [OriontekTest]    Script Date: 08/30/2021 8:44:28 AM ******/
CREATE DATABASE [OriontekTest]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OriontekTest', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\OriontekTest.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OriontekTest_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\OriontekTest_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [OriontekTest] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OriontekTest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [OriontekTest] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [OriontekTest] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [OriontekTest] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [OriontekTest] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [OriontekTest] SET ARITHABORT OFF 
GO
ALTER DATABASE [OriontekTest] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [OriontekTest] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [OriontekTest] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [OriontekTest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [OriontekTest] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [OriontekTest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [OriontekTest] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [OriontekTest] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [OriontekTest] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [OriontekTest] SET  DISABLE_BROKER 
GO
ALTER DATABASE [OriontekTest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [OriontekTest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [OriontekTest] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [OriontekTest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [OriontekTest] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [OriontekTest] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [OriontekTest] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [OriontekTest] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [OriontekTest] SET  MULTI_USER 
GO
ALTER DATABASE [OriontekTest] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [OriontekTest] SET DB_CHAINING OFF 
GO
ALTER DATABASE [OriontekTest] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [OriontekTest] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [OriontekTest] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [OriontekTest] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [OriontekTest] SET QUERY_STORE = OFF
GO
USE [OriontekTest]
GO
/****** Object:  Table [dbo].[Company]    Script Date: 08/30/2021 8:44:28 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Company](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[IsActive] [bit] NOT NULL,
 CONSTRAINT [PK_Company] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Customer]    Script Date: 08/30/2021 8:44:28 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customer](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CompanyId] [int] NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[LastName] [varchar](50) NOT NULL,
	[PhoneNumber] [varchar](14) NOT NULL,
	[Email] [varchar](100) NULL,
	[IsActive] [bit] NOT NULL,
 CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CustomerAddress]    Script Date: 08/30/2021 8:44:28 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CustomerAddress](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CustomerId] [int] NOT NULL,
	[Country] [varchar](100) NOT NULL,
	[City] [varchar](100) NOT NULL,
	[Address] [varchar](150) NOT NULL,
	[CountryState] [varchar](100) NOT NULL,
	[PostalCode] [varchar](50) NOT NULL,
	[IsActive] [bit] NOT NULL,
 CONSTRAINT [PK_CustomerAddress] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Customer]  WITH CHECK ADD  CONSTRAINT [FK_Customer_Company] FOREIGN KEY([CompanyId])
REFERENCES [dbo].[Company] ([Id])
GO
ALTER TABLE [dbo].[Customer] CHECK CONSTRAINT [FK_Customer_Company]
GO
ALTER TABLE [dbo].[CustomerAddress]  WITH CHECK ADD  CONSTRAINT [FK_CustomerAddress_Customer] FOREIGN KEY([CustomerId])
REFERENCES [dbo].[Customer] ([Id])
GO
ALTER TABLE [dbo].[CustomerAddress] CHECK CONSTRAINT [FK_CustomerAddress_Customer]
GO
USE [master]
GO
ALTER DATABASE [OriontekTest] SET  READ_WRITE 
GO
